/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package rose.mary.trace.core;

import pep.per.mint.common.util.Util;

public class Library {

  public boolean someLibraryMethod() {
    return true;
  }

  public static void main(String[] args) {
    String value = "";
    System.out.println(Integer.parseInt(Util.isEmpty(value) ? "0" : value));
  }
}
